baseURL: https://xdcyw.tk/
theme: hugo-PaperMod

params:
    homeInfoParams:
        Title: 技術的理想主義者の日記

menu:
    main:
        - identifier: home
          name: home
          url: /
          weight: 10
        - identifier: blog
          name: blog
          url: /post
          weight: 20
        - identifier: profile
          name: profile
          url: profile/profile
          weight: 30

    

