baseURL = 'http://xdcyw.tk/'
languageCode = 'ja'
title = "技術的理想主義者の日記"
theme = 'sam'
favicon = true
publishDir = "docs"
[[params.mainMenu]]
    link = "/post"
    text = "blog"

[[params.mainMenu]]
    link = "/profile/profile/"
    text = "profile"




